apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mssql-compute-pool-node
spec:
  serviceName: service-node
  selector:
    matchLabels:
      app: mssql-compute-pool-node
  replicas: 2
  volumeClaimTemplates:
  - metadata:
      name: pvc
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi
  - metadata:
      name: pvc-hdfs
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 50Gi
  template:
    metadata:
      labels:
        component: mssql-compute-pool-node
        app: mssql-compute-pool-node
    spec:
      terminationGracePeriodSeconds: 0
      volumes:
      - name: secrets
        secret:
          secretName: mssql-compute-pool-secret
      imagePullSecrets:
      - name: mssql-private-registry
      containers:
      - name: mssql-compute-pool-node
        command: ["/init-node.sh"]
        image: private-repo.microsoft.com/mssql-private-preview/mssql-hadoop:latest
        ports:
        - containerPort: 8088
          name: port-8088
        - containerPort: 50070
          name: port-50070
        - containerPort: 50075
          name: port-50075
        - containerPort: 50020
          name: port-50020
        - containerPort: 9000
          name: port-9000
        - containerPort: 50010
          name: port-50010
        - containerPort: 8030
          name: port-8030
        - containerPort: 8031
          name: port-8031
        - containerPort: 8032
          name: port-8032
        - containerPort: 8033
          name: port-8033
        - containerPort: 8040
          name: port-8040
        - containerPort: 8042
          name: port-8042
        volumeMounts:
        - mountPath: "/root/hdfs/"
          name: pvc-hdfs
      - name: mssql-compute-pool-data
        image: private-repo.microsoft.com/mssql-private-preview/mssql-data
        volumeMounts:
        - mountPath: "/var/opt/mssql"
          name: pvc
        - mountPath: "/root/secrets"
          name: secrets
          readOnly: true
        ports:
        - containerPort: 1433
          name: port-1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql-compute-pool-secret
              key: mssql-compute-pool-sa